name: Nicolas Galinotti
favicon: null
layout_spectrum: 0.8371895106974989
typography_spectrum: 0.21092380583286285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4155547455884516
  lightness: 0.268787270411849
  saturation: 0.5980288246646523
  rhythmicContrast: 0.7393673311453313
purpose: []
