name: Nicolas Galinotti
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2462
title: Nicolas Galinotti - Digital Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5d3c0'
    - '#464741'
    - '#a09e90'
    - '#73736a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
