name: Nicolas Galinotti
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73839
title: Nicolas Galinotti - Software Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#21331b'
    - '#636c4f'
    - '#dde9c5'
    - '#80b84a'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
